-- MySQL Script generated by MySQL Workbench
-- Mon Mar  5 15:38:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ECE492Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECE492Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECE492Database` DEFAULT CHARACTER SET utf8 ;
USE `ECE492Database` ;

-- -----------------------------------------------------
-- Table `ECE492Database`.`RemoteSensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECE492Database`.`RemoteSensor` (
  `StationName` VARCHAR(20) NOT NULL,
  `Latitude` DOUBLE NULL,
  `Longitude` DOUBLE NULL,
  `Temperature` DOUBLE NULL,
  `Dust` DOUBLE NULL,
  `Date` DATETIME NOT NULL,
  PRIMARY KEY (`StationName`, `Date`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station1",56,-114,-20,50,"2018-02-13 14:34:55");
INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station1",56,-114,-18,45,"2018-02-13 15:16:21");
INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station1",56,-114,-18,45,"2018-01-24 13:26:41");
INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station2",51,-112,-25,23,"2018-01-11 13:46:23");
INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station3",34,-113,20,100,"2018-02-11 8:04:56");
INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station4",40,-120,15,100,"2018-02-11 8:04:56");
INSERT INTO `remotesensor`(`StationName`, `Latitude`, `Longitude`, `Temperature`, `Dust`, `Date`) VALUES ("Station5",60,-130,5,100,"2018-02-11 8:04:56");